### ISSUE TITLE
Map info popup doesn't disappear.

### ISSUE THREAD

**Issue by SANTOSHKVNSP** [ajc113/currents#18]
On Heatmap (/maps) page, if we click on any area, it opens the info popup.

Clicking on the second location should close the first popup and open the new one.

Instead, the new popup is opened with the first one, which creates the mess in UI.

![image](https://cloud.githubusercontent.com/assets/5381405/22396395/b9d89806-e57e-11e6-87ee-a46baf20e4aa.png)

**Comment by SANTOSHKVNSP** [comment]
@ajc113 can you close the issue if you think it's working fine?

**Comment by ajc113** [comment]
fixed when user selects other polygon current infowindow closes
