### ISSUE TITLE
Prod release  2.7

### ISSUE THREAD

**Issue by ajc113** [ajc113/currents#182]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is `2.8`

**Comment by tannakartikey** [comment]
@rultor release, tag is `2.8`

**Comment by ajc113** [comment]
@rultor release, tag is `2.8.1`

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is `2.8.2`

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is `2.8.3`

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is `2.8.4`

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is `2.8.5`

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is `2.8.6`

**Comment by ajc113** [comment]
@rultor release, tag is `2.8.7`

**Comment by ajc113** [comment]
@rultor release, tag is `2.8.8`

**Comment by ajc113** [comment]
@rultor release, tag is `2.9`

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is `2.10`

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is `2.11`

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is `2.12`

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is `2.13`

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is `2.14`

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is `2.15`

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is `2.16`

**Comment by ajc113** [comment]
@rultor release, tag is `2.17`

**Comment by ajc113** [comment]
@rultor deploy
