### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (NoMethodError) "undefined method `subscription_id=' for nil:NilClass"

### ISSUE THREAD

**Issue by ajc113** [ajc113/currents#184]
<table><tr><th>Exception</th><td>undefined method `subscription_id=&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>April 03, 2018 18:14:21 +0000</td></tr><tr><th>Count</th><td>5</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/ajc113/currents/blob/63c8cfa58213ef2d916f1f904c4e02cf3dbe9859/app/controllers/stripe_controller.rb#L42'>[app].../app/controllers/stripe_controller.rb:42:in `event_process'</a>
<a href='https://github.com/ajc113/currents/blob/63c8cfa58213ef2d916f1f904c4e02cf3dbe9859/app/controllers/stripe_controller.rb#L23'>[app].../app/controllers/stripe_controller.rb:23:in `block in events'</a></pre>
Fingerprint: `01285599748f57df377d1033463fc8ac9c4f7cf6`

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>February 07, 2018 17:34:23 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
Not sure if Stripe customer ID is being created because of this issue.

**Comment by tannakartikey** [comment]
@ajc113 the Stripe customer is being created successfully.

The error is related to a cancellation of the subscription. I canceled one subscription and seems to be working fine. I am closing the issue for now.

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>February 10, 2018 17:04:06 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>February 21, 2018 02:42:28 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>March 06, 2018 01:36:47 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by ajc113** [comment]
<table><tr><th>Occurred At</th><td>April 03, 2018 18:14:21 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CCte7DyDCrOMJ6Ppiy1zwgb</td></tr></table></td></tr></table>
