### ISSUE TITLE
New Theme

### ISSUE THREAD

**Issue by tannakartikey** [ajc113/currents#214]
Mapping

Root index - Index 35.html
About - aboutme3.html
Intel index - blog-right-sidebar.html
Posts index - blog-classic-full-width.html
Spots index - blog-list-right-sidebar.html
Intel, Post, Spot - show pages all - single.html
Maps index - Index32.html map section only
Report - elements-tables.html (Table Hover for reports table)

Concerns

Template uses retina.js for high res images applying (@2x, @3x, etc) to denote high-res image variants on server. Unsure how this will impact AWS and production.  https://github.com/joshuajansen/retinajs-rails/issues/5

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is `3.0`

**Comment by tannakartikey** [comment]
@rultor deploy

**Comment by tannakartikey** [comment]
@rultor deploy

**Comment by tannakartikey** [comment]
@rultor deploy

**Comment by tannakartikey** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor deploy

**Comment by tannakartikey** [comment]
@rultor deploy

**Comment by tannakartikey** [comment]
@rultor stop

**Comment by tannakartikey** [comment]
@rultor deploy

**Comment by tannakartikey** [comment]
@rultor stop

**Comment by tannakartikey** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor deploy

**Comment by tannakartikey** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is ‘3.0’

**Comment by ajc113** [comment]
@rultor release, tag is `3.0`

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is `3.1`

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is `3.2`

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is `3.3`

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is `3.31`

**Comment by ajc113** [comment]
@rultor deploy

**Comment by ajc113** [comment]
@rultor release, tag is `3.3.2`

**Comment by ajc113** [comment]
@rultor release, tag is 3.32

**Comment by ajc113** [comment]
@rultor release, tag is `3.32`
