### ISSUE TITLE
Test for availability of reports for each location

### ISSUE THREAD

**Issue by SANTOSHKVNSP** [ajc113/currents#32]
With this change https://github.com/ajc113/currents/commit/c2f9abf7704cf33c4505fac206b022e9fda99134#diff-4dc608199f527c9e61542f3c0fcfd98bL16 we removed the earlier error of the code.

But it's still manual efforts to check for the availability of the reports. It's not feasible to iterate through each folder manually every time and mistake in the process can break the code.

We should have automated testing for this so that users don't face any breakages and developers don't have to invest effort in checking files 

Test can run locally and also on our staging environment.

@ajc113 what do you think?

**Comment by tannakartikey** [comment]
The Rake task has been created for the solution. 
Command `rake checklocation:files` invokes the task.
The following checks are done by the task:
- First of all, counts of location in the database is compared with the count of the folders present under `public/uploads/lcoation/coordinate_file`. On a high level we can know if the coordinate files are present or not.
- Then, for each record in the Location the following checks are made:
  - If folder exist for the location
  - If there are more than one file in the folder
  - If the extension of the file is json or not
  - If the filename starts with the id of the location
